// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH4oBsy0epJmuRuHPEWHboLkLIMzI7UzU',
    appId: '1:73355516548:android:77f93a1c627ea4c00500d1',
    messagingSenderId: '73355516548',
    projectId: 'whoareyo-u',
    storageBucket: 'whoareyo-u.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf6LT12M7m8og2PRkhkwaLU3OuZl2ct6U',
    appId: '1:73355516548:ios:4041e35d1bf616da0500d1',
    messagingSenderId: '73355516548',
    projectId: 'whoareyo-u',
    storageBucket: 'whoareyo-u.appspot.com',
    iosClientId: '73355516548-pn7npldftb23ta6gr1bsnhqvjrglhm61.apps.googleusercontent.com',
    iosBundleId: 'com.example.nugu',
  );
}
